name: health_modelling
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - notebook
  - jupyterlab
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - altair
  - statsmodels
  - requests
  - openpyxl
  - pyarrow
  - xlrd
  - json5
  - tqdm
  - pip
  - pip:
      - fingertips-py  # If you choose to use a wrapper library (optional)
      - pyreadstat      # For STATA/SAV files if needed
